### ISSUE TITLE
Why does the  client side have to turn on the terminal and type: curl http://localhost:3000/users? 

### ISSUE THREAD

**Issue by JHYen1978** [onedesign/express-socketio-tutorial#13]
Hi brianjhanson,

First of all I really like the project and the introduction you provided is very clear and comprehensive. 

However, I am not sure about the final part of the introduction. That is, why do we first open up homepage at http://localhost:3000, and then pop open terminal and type: curl http://localhost:3000/users?  Why does it not just done in Chrome (or other browser)? 

If we would like to use express-socket.io to build a instant messaging system working on browsers, how do we do if users do not want to turn on the terminal in addition to browsers?

Thank you very much and look forward to your further instruction.

JHYen

**Comment by brianjhanson** [comment]
Hey @JHYen1978,

Thanks! I can't take any credit for writing it, but I'm glad you've enjoyed it.

There's no real reason we `curl` instead of visiting the site in another browser, it's only because it was a little quicker and easier to explain. Are you having issues trying to get things working when visiting `localhost:3000/users` in another browser?

**Comment by JHYen1978** [comment]
Hi @brianjhanson ,

I am so glad to receive the reply from you.  

Now I have no problem linking to `http://localhost:3000/users` either using `curl` or visiting the site in another browser. I was very confused about how this example work, but now I think I get it. Correct me if my understanding is incorrect: if we turn on two browsers say, A and B, A goes to `http://localhost:3000/users` and B goes to `http://localhost:3000` respectively, it will act like A is a message sender and B is a receiver, right? 

Based on this example, I should be able to build a web-based instant messaging platform on which A and B can do real-time chatting. If you know something like this (be sure using express-generator + socket.io) has been on shelf in github or elsewhere, please be so kind to give me the link to it.

Thank you very much!

**Comment by OldGitDave** [comment]
Hi Brian,
My wife became ill two years ago and died. I’m afraid I lost interest in this thread.
Sorry for any inconvenience.
All the best
Dave
PS I could not remember my GitHub password…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by brianjhanson** [comment]
Very sorry to hear that @OldGitDave. I've closed the issue for now, but feel free to open it back up if  needed in the future.
