### ISSUE TITLE
When trying localhost:3000 i get GET http://localhost:3000/ net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by CMode11** [onedesign/express-socketio-tutorial#5]
When trying localhost:3000 i get GET http://localhost:3000/ net::ERR_CONNECTION_REFUSED
This happens when copying and using the file from   git clone
Chrome console gives no indication of why this is failing

**Comment by SendDerek** [comment]
I just cloned this project myself and attempted to run `DEBUG=myapp:* npm start`.  I noticed port 3000 wasn't working, but after reviewing _bin/www_, the author changed it to 3004.  Probably to avoid conflicts with other node.js projects they're working on.  So, try and visit http://localhost:3004 instead.

**Comment by danboy** [comment]
Updated the port to 3000
