### ISSUE TITLE
Is this solution still valid?

### ISSUE THREAD

**Issue by KeyingXu** [onedesign/express-socketio-tutorial#9]
I downloaded this repo and run it on my laptop. Following the tutorial, I'm supposed to see the "users" in my dev tools console output at the end. But nothing shows up in my console output. Since the repo is about 2-3 years ago, does that mean some dependencies could change since then so that it's not working anymore. Could anybody kindly try this repo and let me know whether it succeeds or not? Thank you in advance.

**Comment by KeyingXu** [comment]
Sorry, my fault. The solution actually works perfect. 
Refer to this post (https://github.com/onedesign/express-socketio-tutorial/issues/4). I understand that if we don't use curl post, then both webpages  http://localhost:3000 and http://localhost:3000/users are open in order to observe the socket.io emitted message "users".

**Comment by brianjhanson** [comment]
Thanks @KeyingXu! Glad you got it sorted out.
